apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 1m

    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 2m
      receiver: 'default-receiver'

    receivers:
      - name: 'default-receiver'
        email_configs:
          - to: '${EMAIL_TO}'
            from: '${EMAIL_FROM}'
            smarthost: 'smtp.gmail.com:587'
            auth_username: '${SMTP_USER}'
            auth_password: '${SMTP_PASS}'
            send_resolved: true
