apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
spec:
  replicas: 2  # High availability
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.27.0
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
            - "--storage.path=/alertmanager"
            - "--log.level=info"
            - "--web.listen-address=0.0.0.0:9093"
          ports:
            - containerPort: 9093
          env:
            - name: EMAIL_TO
              valueFrom:
                secretKeyRef:
                  name: alertmanager-credentials
                  key: email_to
            - name: EMAIL_FROM
              valueFrom:
                secretKeyRef:
                  name: alertmanager-credentials
                  key: email_from
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: alertmanager-credentials
                  key: smtp_user
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: alertmanager-credentials
                  key: smtp_pass
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9093
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9093
            initialDelaySeconds: 10
            periodSeconds: 15
          volumeMounts:
            - name: alertmanager-config
              mountPath: /etc/alertmanager/alertmanager.yml
              subPath: alertmanager.yml
      volumes:
        - name: alertmanager-config
          configMap:
            name: alertmanager-config
