apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-basic-auth
  namespace: monitoring
type: Opaque
stringData:
  smtp_user: "no-reply@example.com"
  smtp_pass: "change_me"
  email_to: "alerts-team@example.com"
  email_from: "no-reply@example.com"
