apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-credentials
  namespace: monitoring
type: Opaque
stringData:
  email_to: "raguls200010@example.com"
  email_from: "alertmanager123123@example.com"
  smtp_user: "alertmanager123123@example.com"
  smtp_pass: "richard123"
