apiVersion: v1
kind: ConfigMap
metadata:
  name: remediator-policies
  namespace: monitoring
data:
  policies.yaml: |
    HighCPUUsage: "kubectl scale deployment module-2-sample-app --replicas=5"
    PodCrashLoop: "kubectl rollout restart deployment module-2-sample-app"
    BadImageDetected: "kubectl rollout undo deployment module-2-sample-app"
    SuspiciousPod: "kubectl cordon pod suspicious-pod-name"
    MemoryOverload: "kubectl scale deployment module-2-sample-app --replicas=3"
