apiVersion: apps/v1
kind: Deployment
metadata:
  name: remediator
  namespace: monitoring
  labels:
    app: remediator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remediator
  template:
    metadata:
      labels:
        app: remediator
    spec:
      containers:
        - name: remediator
          image: remediator:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: policies-volume
              mountPath: /app/policies.yaml
              subPath: policies.yaml
      volumes:
        - name: policies-volume
          configMap:
            name: remediator-policies
